In [1]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
list1 = [10, 20, 30, 40, 50, 60]
list1

[10, 20, 30, 40, 50, 60]

In [3]:
type(list1)

list

In [4]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [5]:
arr1.data

In [7]:
type(arr1) #display type

numpy.ndarray

In [8]:
arr1.dtype

dtype('int32')

In [9]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [15]:
arr3 = np.arange(0, 10)
arr3.shape

(10,)

In [16]:
arr3.size

10

In [17]:
arr3.ndim

1

In [18]:
arr3.itemsize

4

In [19]:
arr3.nbytes

40

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.repeat(10, 8)

array([10, 10, 10, 10, 10, 10, 10, 10])

In [26]:
a = np.array([10, 20, 30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [27]:
np.full(8, 10)

array([10, 10, 10, 10, 10, 10, 10, 10])

In [28]:
ar1 = np.arange(1, 20)
ar1[ar1 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
ar1 = np.arange(1, 20)
ar1[ar1 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [31]:
np.linspace(10, 20, 11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [32]:
np.random.random(4)

array([0.53987495, 0.33274165, 0.32689219, 0.09500888])

In [33]:
np.random.randint(0, 500, 5)

array([172, 272, 450, 429, 111])

In [34]:
np.random.randint(0, 500, 10)

array([406, 489,  19, 283, 209, 403, 402,  60, 188, 243])

In [37]:
f1 = np.random.uniform(5, 10, size=(10))
f1

array([5.08358047, 9.26841642, 8.53062931, 5.49265692, 7.88834628,
       9.75857135, 9.00978892, 9.86327647, 7.2173457 , 8.04138658])

In [38]:
np.floor(f1)

array([5., 9., 8., 5., 7., 9., 9., 9., 7., 8.])

In [39]:
np.trunc(f1)

array([5., 9., 8., 5., 7., 9., 9., 9., 7., 8.])

In [40]:
f1.astype(int)

array([5, 9, 8, 5, 7, 9, 9, 9, 7, 8])

In [42]:
b2 = np.random.randn(10)
b2

array([-1.64043831, -2.55029835,  0.34561651,  0.33928358,  0.81505025,
        0.55257079,  1.58285981, -0.31220924,  1.67813022, -1.94996201])

In [43]:
arr2 = np.arange(1, 20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [44]:
arr2.sum()

190

In [45]:
np.cumsum(arr2) #cumulative sum

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [ ]:
arr2.min(), max()

In [46]:
arr2.argmin()

0

In [47]:
arr2.argmax()

18

In [48]:
arr2.mean()

10.0

In [50]:
np.var(arr2)

30.0

In [51]:
np.std(arr2)

5.477225575051661

In [52]:
A = np.array([[1, 2, 3, 0], [5, 6, 7, 22], [10, 11, 1, 13], [14, 15, 16, 3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [53]:
A.sum()

129

In [54]:
np.amin(A, axis = 0)

array([1, 2, 1, 0])

In [55]:
np.amin(A, axis = 1)

array([0, 5, 1, 3])

In [56]:
A.mean()

8.0625

In [57]:
np.std(A)

6.348904925260734

In [58]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [59]:
a = np.array([7, 5, 3, 9, 0, 2])
a

array([7, 5, 3, 9, 0, 2])

In [60]:
a[1:4]

array([5, 3, 9])

In [61]:
a[-3:-1]

array([9, 0])

In [62]:
ar = np.arange(1, 20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [63]:
rep1 = np.where(ar % 2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [65]:
ar2 = np.array([10, 20, 30, 10, 10, 20, 20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [67]:
rep2 = np.where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [68]:
a = np.array([10, np.nan, 20, 30, 60, np.nan, 90, np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [69]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [70]:
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [71]:
a[np.isnan(a)] = 99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [ ]:
A = np.array([[1,2,np.nan,4] , [np.nan,6,7,8] , [10 , np.nan , 12 ,13] , [14,15,16,17]])

In [72]:
a = np.zeros(20).reshape(2, -1)
b = np.repeat(1, 20).reshape(2, -1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [73]:
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [74]:
np.vstack([a, b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [75]:
np.hstack([a, b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [77]:
c1 = np.array([10, 20, 30, 40, 50, 60])
c2 = np.array([12, 20, 33, 40, 55, 60])
np.intersect1d(c1, c2)

array([20, 40, 60])

In [79]:
np.setdiff1d(c2, c1)

array([12, 33, 55])

In [80]:
a4 = np.arange(10, 30)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [81]:
a4[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [82]:
np.flip(a4)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [83]:
a3 = np.array([[3, 2, 8, 1], [70, 50, 10, 67], [45, 25, 75, 15], [12, 9, 77, 4]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15],
       [12,  9, 77,  4]])

In [84]:
a3[::-1,]

array([[12,  9, 77,  4],
       [45, 25, 75, 15],
       [70, 50, 10, 67],
       [ 3,  2,  8,  1]])

In [85]:
a3[:,::-1]

array([[ 1,  8,  2,  3],
       [67, 10, 50, 70],
       [15, 75, 25, 45],
       [ 4, 77,  9, 12]])

In [86]:
a3[::-1, ::-1]

array([[ 4, 77,  9, 12],
       [15, 75, 25, 45],
       [67, 10, 50, 70],
       [ 1,  8,  2,  3]])

In [87]:
p1 = np.arange(0, 121).reshape(11,11)
p1

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [88]:
np.save('test1.npy', p1)

In [89]:
p2 = np.load('test1.npy')
p2

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [90]:
np.save('numpyfile', p1)

In [91]:
p3 = np.load('numpyfile.npy')
p3

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [92]:
p4 = np.arange(0, 1000000).reshape(1000, 1000)
p4

array([[     0,      1,      2, ...,    997,    998,    999],
       [  1000,   1001,   1002, ...,   1997,   1998,   1999],
       [  2000,   2001,   2002, ...,   2997,   2998,   2999],
       ...,
       [997000, 997001, 997002, ..., 997997, 997998, 997999],
       [998000, 998001, 998002, ..., 998997, 998998, 998999],
       [999000, 999001, 999002, ..., 999997, 999998, 999999]])

In [93]:
np.savez_compressed('test2.npz', p4)

In [94]:
np.save('test3.npy', p4)

In [95]:
from IPython.display import Image

In [98]:
v1 = np.array([1, 2])
v2 = np.array([3, 4])
#v3 = v1 + v2
v3 = np.add(v1, v2)
print('V3 :- ',v3)

V3 :-  [4 6]


In [106]:
p = np.loadtxt('sample.txt', dtype = np.integer)
p

array([[24, 29, 88],
       [ 1,  0,  8],
       [33,  7, 99],
       [39, 11, 98],
       [22, 76, 87]])

In [107]:
p5 = np.genfromtxt('sample0.txt', dtype = 'str')
p5

array([['Dogu', 'Turkey', 'Football'],
       ['John', 'USA', 'Hockey'],
       ['Paul', 'Canada', 'Basketball']], dtype='<U10')

In [108]:
np.loadtxt('sample.txt', delimiter = ' ', usecols = (0, 2))

array([[24., 88.],
       [ 1.,  8.],
       [33., 99.],
       [39., 98.],
       [22., 87.]])

In [114]:
a1 = [5, 6, 7]
a2 = [4, 7, 9]
print(np.multiply(a1, a2))

[20 42 63]


In [116]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

dotp = a1@a2
print("Dot product :- ", dotp)

Dot product :-  32


In [117]:
dotp = np.dot(a1, a2)
print("Dot product using function:- ", dotp)

Dot product using function:-  32


In [118]:
dotpinner = np.inner(a1, a2)
print(dotpinner)

32


In [119]:
print(sum(np.multiply(a1, a2)))

32


In [120]:
dotp = np.matmul(a1, a2)
print(dotp)

32


In [121]:
dotp = 0
for i in range(len(a1)):
    dotp = dotp + a1[i] * a2[i]
print(dotp)

32


In [122]:
v3 = np.array([1, 2, 3, 4, 5, 6])
length = np.sqrt(np.dot(v3, v3))
length

9.539392014169456

In [123]:
#Vektör nasıl normalize edilir?
v1 = [2, 3]
length_v1 = np.sqrt(np.dot(v1, v1))
norm_v1 = v1 / length_v1
length_v1, norm_v1

(3.605551275463989, array([0.5547002 , 0.83205029]))

In [124]:
v1 = [2, 3]
norm_v1 = v1 / np.linalg.norm(v1)
norm_v1

array([0.5547002 , 0.83205029])

In [ ]:
np.rad2deg

In [125]:
mat1 = np.random.randint(0, 1000, 100).reshape(10, 10)
mat1

array([[ 12, 342, 318, 436, 350, 602, 873, 458, 173, 302],
       [700,  74, 242, 381,  13, 105, 641, 207, 951, 909],
       [153, 997, 616, 292, 465, 200,  83, 681, 541, 143],
       [942, 923, 803, 987, 787, 837, 112, 761, 630, 155],
       [519, 758, 657, 503, 514, 979,  86, 499, 459, 383],
       [493,  56, 826, 769, 292, 553, 106,  81, 500, 596],
       [ 73, 229, 313, 948, 628, 394, 294, 884, 502,  35],
       [245, 132, 213, 872, 674, 557, 821, 396, 854, 942],
       [ 58, 790, 905, 889, 972, 908, 412,  93, 902, 717],
       [450, 807, 290,  34, 829, 696, 476, 892, 104, 643]])

In [126]:
mat1[mat1 > 500]

array([602, 873, 700, 641, 951, 909, 997, 616, 681, 541, 942, 923, 803,
       987, 787, 837, 761, 630, 519, 758, 657, 503, 514, 979, 826, 769,
       553, 596, 948, 628, 884, 502, 872, 674, 557, 821, 854, 942, 790,
       905, 889, 972, 908, 902, 717, 807, 829, 696, 892, 643])

In [128]:
I = np.eye(9) #identity (birim) matris
I 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [129]:
D = np.diag([1, 2, 3, 4, 5, 6, 7, 8]) #diagonal matris
D

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [130]:
M = np.random.randn(5, 5)
U = np.triu(M)
L = np.tril(M)
print(M)

[[ 1.65270839 -0.06620512 -0.29779697 -0.13947548 -0.25067725]
 [ 1.49994876 -0.65105374 -1.74733497 -0.45299874  1.33390266]
 [-0.7407273  -0.67849435  1.60255493  0.55249304  1.44357818]
 [-0.8487259   2.29281315 -1.45364849  0.16052775  0.31139334]
 [ 0.4561762   0.83344595  1.61108405  1.42348679  1.11699162]]


In [131]:
print(U)

[[ 1.65270839 -0.06620512 -0.29779697 -0.13947548 -0.25067725]
 [ 0.         -0.65105374 -1.74733497 -0.45299874  1.33390266]
 [ 0.          0.          1.60255493  0.55249304  1.44357818]
 [ 0.          0.          0.          0.16052775  0.31139334]
 [ 0.          0.          0.          0.          1.11699162]]


In [132]:
print(L)

[[ 1.65270839  0.          0.          0.          0.        ]
 [ 1.49994876 -0.65105374  0.          0.          0.        ]
 [-0.7407273  -0.67849435  1.60255493  0.          0.        ]
 [-0.8487259   2.29281315 -1.45364849  0.16052775  0.        ]
 [ 0.4561762   0.83344595  1.61108405  1.42348679  1.11699162]]


In [133]:
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])
print(M)

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]


In [134]:
np.transpose(M)

array([[ 1,  4,  7],
       [ 2, -3,  8],
       [ 3,  6,  0]])

In [135]:
M.T

array([[ 1,  4,  7],
       [ 2, -3,  8],
       [ 3,  6,  0]])

In [136]:
np.linalg.det(M)

195.0

In [137]:
np.linalg.inv(M)

array([[-0.24615385,  0.12307692,  0.10769231],
       [ 0.21538462, -0.10769231,  0.03076923],
       [ 0.27179487,  0.03076923, -0.05641026]])

In [138]:
N = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print(M/N)

[[ 1.          2.          3.        ]
 [ 2.         -1.5         3.        ]
 [ 2.33333333  2.66666667  0.        ]]


In [139]:
np.divide(M,N)

array([[ 1.        ,  2.        ,  3.        ],
       [ 2.        , -1.5       ,  3.        ],
       [ 2.33333333,  2.66666667,  0.        ]])

In [140]:
M1 = np.array([[1,2],[4,5]])
M1

array([[1, 2],
       [4, 5]])

In [141]:
M1@M1@M1

array([[ 57,  78],
       [156, 213]])

In [142]:
np.linalg.matrix_power(M1, 3)

array([[ 57,  78],
       [156, 213]])

In [ ]:
#tensor, upgraded matrix

In [144]:
T1 = np.array([
    [[1,2,3], [4, 5, 6], [7,8,9]],
    [[10,20,30], [40,50,60], [70,80,90]],
    [[100,200,300], [400,500,600], [700,800,900]],
])

T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [145]:
T2 = np.array([
    [[0,0,0], [0,0,0], [0,0,0]],
    [[1,1,1], [1,1,1], [1,1,1]],
    [[2,2,2], [2,2,2], [2,2,2]],
])

T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [147]:
A = T1 + T2
A

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [148]:
D = T1 / T2
D

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])